name: Docker Image CI
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  status:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REPO_NAME: "devbox"
  REF_NAME: "latest"
  DOCKER_USERNAME: ""
  DOCKER_PASSWORD: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Docker User info
        run: |
          echo "$DOCKER_USERNAME"
          echo "$DOCKER_PASSWORD"
          
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ env.DOCKER_USERNAME }}  # Docker Hub ç”¨æˆ·å
          password: ${{ env.DOCKER_PASSWORD }}  # Docker Hub å¯†ç 

      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ env.REF_NAME }}  # æ›¿æ¢ä¸ºä½ çš„ Docker Hub ç”¨æˆ·åå’Œé•œåƒåç§°
          
      - name: Print Docker images
        run: |
          docker images
          echo $(basename "$(pwd)")
        
      - name: Logout from Docker Hub
        run: docker logout
    
